--liquibase formatted sql

--changeset MarinaGubina:1
CREATE TABLE IF NOT EXISTS notification_tasks
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                BIGINT       NOT NULL,
    description            TEXT NOT NULL,
    date_time              TIMESTAMP    NOT NULL
);
